# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regression_ideal',
            fields=[
                ('receptor_rut', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('date_min', models.DateTimeField()),
            ],
        ),
    ]
