# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:53
from __future__ import unicode_literals
import pandas as pd
from django.db import migrations

from Gosocket import settings
from regression.models import Regression_ideal


class Migration(migrations.Migration):
    def create_csv_model(apps, schema_editor):
        df = pd.read_csv(settings.CSV_PATH)

        for i in df.values:
            id, a, b, c = i
            Regression_ideal.objects.create(receptor_rut=a, quantity=b, date_min=c)

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_csv_model)
    ]
